---
- name: Scheduling GoAccess in cron
  ansible.builtin.cron:
    name: goaccess_docker
    minute: "{{ goaccess_docker_cron_minute }}"
    hour: "{{ goaccess_docker_cron_hour }}"
    user: "{{ goaccess_docker_cron_user }}"
    job: "eval $(cat {{ goaccess_docker_base_dir }}/goaccess/.env) {{ goaccess_docker_base_dir }}/goaccess/scripts/run-goaccess-rotate"
    cron_file: goaccess_docker
  when: goaccess_docker_cron_enable
